-- @description DF95: Build IFLS Main Toolbar as real .ReaperMenuSet (importable)
-- @version 1.0.0
-- @author DF95 (generated by Reaper DAW Ultimate Assistant)
-- @about
--   Creates an importable MenuSet containing a ready-to-import "Floating toolbar 1" for IFLS Main.
--   It auto-registers the referenced scripts (so they get stable _RS... command IDs), then writes:
--     REAPER\ResourcePath\MenuSets\IFLS_Main.Toolbar.ReaperMenuSet
--
--   After running:
--     Options > Customize menus/toolbars... > select "Floating toolbar 1 (Toolbar 1)"
--     Import... > choose IFLS_Main.Toolbar.ReaperMenuSet
--
-- Notes:
--   - Requires the scripts to be installed at the expected paths under REAPER\ResourcePath\Scripts\
--   - Safe to run multiple times (overwrites the .ReaperMenuSet)

local function msg(s) reaper.ShowConsoleMsg(tostring(s) .. "\n") end
local function join(a,b)
  if not a or a=="" then return b end
  local last=a:sub(-1)
  if last=="\\" or last=="/" then return a..b end
  return a.."/"..b
end
local function exists(path)
  local f=io.open(path,"rb")
  if f then f:close(); return true end
  return false
end
local function ensure_dir(path) reaper.RecursiveCreateDirectory(path,0) end

-- Register a script as an action and return named command string like "_RS...."
local function ensure_named_command(script_abs_path, sectionID)
  if not exists(script_abs_path) then return nil, "missing: "..script_abs_path end

  -- Add script to action list (commit=true)
  local cmdID = reaper.AddRemoveReaScript(true, sectionID, script_abs_path, true)
  if not cmdID or cmdID == 0 then
    return nil, "AddRemoveReaScript failed for: "..script_abs_path
  end

  -- Reverse lookup gives string WITHOUT leading underscore (per REAPER API header docs)
  local name = reaper.ReverseNamedCommandLookup(cmdID)
  if not name or name == "" then
    return nil, "ReverseNamedCommandLookup failed for cmdID="..tostring(cmdID)
  end

  return "_"..name, nil
end

-- ====== CONFIG: map toolbar buttons to scripts ======
-- Adjust only if your repo paths differ.
local resource = reaper.GetResourcePath()
local scripts_root = join(resource, "Scripts")

local buttons = {
  {label="IFLS Beat Control Center", script_rel="IFLS/IFLS/Hubs/IFLS_BeatControlCenter_ImGui.lua"},
  {label="IFLS Artist Hub",         script_rel="IFLS/IFLS/Hubs/IFLS_ArtistHub_ImGui.lua"},
  {label="IFLS SampleGalaxy",       script_rel="IFLS/IFLS/Hubs/IFLS_SampleLibraryHub_ImGui.lua"},
  {label="IFLS Groove & Rhythm",    script_rel="IFLS/IFLS/Hubs/IFLS_PolyRhythmHub_ImGui.lua"},
  {label="IFLS Macros & Scenes",    script_rel="IFLS/IFLS/Hubs/IFLS_SceneHub_ImGui.lua"},
  {label="IFLS FX Brain",           script_rel="IFLS/IFLS/Hubs/IFLS_MasterHub_ImGui.lua"},
  {label="IFLS Diagnostics / Inspector", script_rel="IFLS/DF95/DF95_Diagnostics_Insight_Run.lua"},
  {label="IFLS Dev / Debug",        script_rel="IFLS/IFLS/Domain/IFLS_Diagnostics_DebugDemo.lua"},
}

-- MAIN
reaper.ClearConsole()
msg("DF95: Build IFLS Main Toolbar MenuSet (importable)")
msg("ResourcePath: "..resource)

-- Section ID for Main actions
local SECTION_MAIN = 0

-- Resolve commands
local resolved = {}
local ok_count, fail_count = 0, 0
for i, b in ipairs(buttons) do
  local abs = join(scripts_root, b.script_rel)
  local named, err = ensure_named_command(abs, SECTION_MAIN)
  if named then
    ok_count = ok_count + 1
    resolved[#resolved+1] = {idx=i-1, cmd=named, label=b.label}
    msg(("  OK  %d: %s  ->  %s"):format(i-1, b.label, named))
  else
    fail_count = fail_count + 1
    resolved[#resolved+1] = {idx=i-1, cmd="_", label=b.label} -- placeholder, importable but inert
    msg(("  FAIL %d: %s  (%s)"):format(i-1, b.label, tostring(err)))
  end
end

-- Write MenuSet
local menuSets = join(resource, "MenuSets")
ensure_dir(menuSets)

local out_path = join(menuSets, "IFLS_Main.Toolbar.ReaperMenuSet")

-- Reaper-menu.ini compatible toolbar export section
-- We target Floating toolbar 1 (Toolbar 1) to match your screenshot context.
local f = assert(io.open(out_path, "wb"))

f:write("; DF95/IFLS - IFLS Main Toolbar (generated)\n")
f:write("; Import into: Options > Customize menus/toolbars... > Floating toolbar 1 (Toolbar 1) > Import...\n\n")
f:write("[Floating toolbar 1]\n")
f:write("title=IFLS Main\n\n")

for _, it in ipairs(resolved) do
  f:write(("ACT %d 0 %s\n"):format(it.idx, it.cmd))
  f:write(("ITEM %d %s\n\n"):format(it.idx, it.label))
end

f:close()

msg("")
msg(("Wrote: %s"):format(out_path))
msg(("Resolved: %d OK, %d missing"):format(ok_count, fail_count))
msg("")
msg("NEXT STEPS:")
msg("1) Options > Customize menus/toolbars...")
msg("2) Select: Floating toolbar 1 (Toolbar 1)")
msg("3) Click: Import...")
msg("4) Choose: IFLS_Main.Toolbar.ReaperMenuSet")
msg("5) If some buttons are inert: missing scripts must be installed at the expected paths above.")
